# Generated by Django 4.2.5 on 2024-03-03 02:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyModel",
        ),
    ]
